### ISSUE TITLE
SPD: Aggregation

### ISSUE THREAD

**Issue by kjuli** [PalladioSimulator/Palladio-Analyzer-Slingshot-Extension-SPD-Interpreter#3]
This is about the SPD aggregation, not Monitoring!

**Comment by stiesssh** [comment]
`aggregation` of  `ManagedElementStateStimulus`.

**Comment by kjuli** [comment]
* aggregation at the beginning of the pipeline, pass it to the constraint and trigger checkers

**Comment by klinakuf** [comment]
Part of PR#11, please have a look when reviewing.
